services:
  substreams:
    build: ./substreams
    command: ["sh", "-c", "./scripts/start_substreams.sh"]
    depends_on:
      - db

  db:
    image: clickhouse/clickhouse-server:latest
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - CLICKHOUSE_DB=near_watch
    volumes:
      - db_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"

volumes:
  db_data: