services:
  api:
    build: ./api
    command: [ "sh", "-c", "./scripts/start_api.sh" ]
    volumes:
      - ./api:/app
      - ./substreams/schema.postgresql.sql:/schema.postgresql.sql
    ports:
      - "3000:3000"
    depends_on:
      - db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  substreams:
    build: ./substreams
    command: [ "sh", "-c", "./scripts/start_substreams.sh" ]
    volumes:
      - ./substreams:/app
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=near_river
    volumes:
      - db_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  db_data:
