services:
  api:
    build: ./api
    command: [ "sh", "-c", "./scripts/start_api.sh" ]
    volumes:
      - ./api:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  substreams:
    build: ./substreams
    command: [ "sh", "-c", "./scripts/start_substreams.sh" ]
    volumes:
      - ./substreams:/app
    depends_on:
      - db

  db:
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: near_river
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
